server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movies_db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis:
  type-aliases-package: cn.lym.movies.model
  configuration:
    map-underscore-to-camel-case: true